[workspace]
resolver = "2"
members = [
        "texture-share-ipc",
        "texture-share-vk-base",
        "texture-share-vk-server",
        "texture-share-vk-client",
        "texture-share-gl-client",
]

[profile.release]
strip = true
lto = true
