[package]
name = "texture-share-ipc"
version = "0.1.0"
edition = "2021"

[lib]
#crate-type = ["lib", "cdylib"]

[dependencies]
libc = "0.2.148"
memoffset = "0.9.0"
raw_sync = "0.1.5"
shared_memory = "0.12.4"

[build-dependencies]
cbindgen = "0.26.0"

[dev-dependencies]
tempfile = "3.8.0"

